### ISSUE TITLE
ZegarFinal.obj Missing

### ISSUE THREAD

**Issue by ferrellsl** [qkb2/clock-opengl#1]
ZegarFinal.obj is missing from the /res folder.

**Comment by qkb2** [comment]
Fixed in #d1c7f41

**Comment by ferrellsl** [comment]
What a beautiful clock!  
![image](https://github.com/qkb2/clock-opengl/assets/5926287/d019c71e-e33c-41f5-a47a-e0b90e6ce7b6)
